### ISSUE TITLE
用在OC1.9.0正式版上没有生效

### ISSUE THREAD

**Issue by dgpower** [hmqgg/OctoPrint-core-zh_CN#1]
以前用1.4版本的汉化包，凑合用到1.8.9版本
现到了1.9版本就彻底不管用了
下载了这里最新的，上传更新后不起作用。还是全英文界面

不知道哪里不对

**Comment by hmqgg** [comment]
之前 `zh_CN` 和 `zh` 都能用，现在有限制了就不行了，改天改改

**Comment by dgpower** [comment]
谢谢回复

我找到原因了。是之前我直接从root账号把老版本的翻译文件放到翻译目录里，导致文件权限不对。刚才把旧的删除了，老老实实按你网页方法导进去，重启就生效了

再次感谢你的分享！
